This problem was asked by Quora.

Given a string, find the palindrome that can be made by inserting the fewest number of characters as possible anywhere in the word. If there is more than one palindrome of minimum length that can be made, return the lexicographically earliest one (the first one alphabetically).

For example, given the string "race", you should return "ecarace", since we can add three letters to it (which is the smallest amount to make a palindrome). There are seven other palindromes that can be made from "race" by adding three letters, but "ecarace" comes first alphabetically.

As another example, given the string "google", you should return "elgoogle".

In [6]:
import numpy as np

In [16]:
def palindrominate(s: str) -> str:
    """
    Use dynamic programming, shared sub-state to fill out the costs matrix.
    Then backtrack through the matrix to find the palindrominated string.
    """
    n = len(s)
    costs = np.zeros((n, n), dtype=float)
    path = np.zeros((n, n), dtype=int)  # 0=diag, 1=fromleft, 2=fromabove
    
    # left to right (iterate across rows)
    for i in range(n):
        # top to bottom (iterate down)
        for j in range(n):
            
            marginalcost = 0.0 if s[i] == s[j] else 1.0
            
            fromleft = 0.0 if i == 0 else costs[i-1, j] + 1  # skip char along horizontal axis
            fromabove = 0.0 if j == 0 else costs[i, j-1] + 1  # skip char along vertical axis

            # a diagonal move is only allowed if the two chars are equal, i.e. substitutions are not allowed
            if i > 0 and j > 0 and s[i] == s[j]:
                fromdiag = costs[i-1, j-1]
                
                if fromdiag < fromleft and fromdiag < fromright:
                    costs[i, j] = fromdiag
                    path[i, j] = 0
                elif: 
                
            
            else:
                pass
            
            
            
    
    
    
    
    return 'ecarace'

SyntaxError: invalid syntax (<ipython-input-16-4c1c27d4d47c>, line 8)

In [15]:
assert(palindrominate('race') == 'ecarace')
assert(palindrominate('google') == 'elgoogle')

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


AssertionError: 